//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> categoryid { get; set; }
        public string url_img { get; set; }
        public Nullable<int> unit_id { get; set; }
    
        public virtual category category { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
